name:                ghc-typelits-induction
version:             0.1.0.0
github:              "githubuser/ghc-typelits-induction"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ghc-typelits-induction#readme>

dependencies:
- base >= 4.7 && < 5
- ghc
- ghc-typelits-natnormalise
- ghc-typelits-extra
- ghc-typelits-knownnat
- ghc-tcplugins-extra

ghc-options:
- -fplugin=GHC.TypeLits.Normalise
- -fplugin=GHC.TypeLits.Extra.Solver
- -fplugin=GHC.TypeLits.KnownNat.Solver
- -Wall

library:
  source-dirs: src


tests:
  ghc-typelits-induction-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghc-typelits-induction
